# name: Generate snake animation

# on:
#   schedule: # execute every 12 hours
#     - cron: "0 */12 * * *"

#   workflow_dispatch:

#   push:
#     branches:
#     - master

# jobs:
#   generate:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       # Checkout the repository
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       # Generate snake.svg
#       - name: Generate snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: MehediHasan-dev  # Correctly reference the GitHub username
#           outputs: dist/snake.svg?palette=github-light

#       # Push the snake.svg to the output branch
#       - name: Push snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the GitHub token is properly referenced




name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: MehediHasan-dev
          outputs: dist/snake.svg

      # Step to update the SVG background color to white
      - name: Change Snake SVG Background Color to White
        run: |
          sed -i 's/<svg /<svg style="background-color:white;" /' dist/snake.svg

      - name: Push Snake SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
