# name: Generate snake animation

# on:
#   schedule: # execute every 12 hours
#     - cron: "0 */12 * * *"

#   workflow_dispatch:

#   push:
#     branches:
#     - master

# jobs:
#   generate:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       # Checkout the repository
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       # Generate snake.svg
#       - name: Generate snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: MehediHasan-dev  # Correctly reference the GitHub username
#           outputs: dist/snake.svg?palette=github-light

#       # Push the snake.svg to the output branch
#       - name: Push snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the GitHub token is properly referenced





name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Generate the snake.svg using the correct GitHub username and palette
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: MehediHasan-dev  # Your GitHub username
          outputs: dist/snake.svg?palette=github-light  # Light palette for the background

      # Step 3: Push the generated snake.svg to the output branch
      - name: Push Snake SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Push the SVG to the output branch
          build_dir: dist        # Directory where the SVG is stored
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
























